### ISSUE TITLE
[Day1] 개발환경 구축

### ISSUE THREAD

**Issue by roseline124** [roseline124/study-buddies-server#1]
# Todos
- [x] 프로젝트 세팅: graphql, express, typescript
- [x] eslint 추가
- [x] code generator 추가
- [x] dotenv 추가
- [x] jest 추가
- [x] sequelize 추가
- [x] RDS 생성 (mysql)
- [ ] schema 폴더 root로 옮기기
- [ ] 배포
  - [ ] ainize
  - dockerignore도 추가하면 좋을 것 같아요

**Comment by roseline124** [comment]
- `yarn build`
- dockerfile
```
FROM node:12
WORKDIR /app
COPY package*.json ./
RUN yarn install --production --frozen-lockfile
COPY . .

EXPOSE 3000

CMD ["yarn", "start"]
```

**Comment by chloe-codes1** [comment]
dockerignore 추가하겠습니다!

**Comment by chloe-codes1** [comment]
Ainize 배포 시 다음과 같은 에러를 뱉음

![image](https://user-images.githubusercontent.com/53922851/87331651-48b6b380-c575-11ea-9912-de2bb0d39ec7.png)

**Comment by roseline124** [comment]
> Ainize 배포 시 다음과 같은 에러를 뱉음
> 
> ![image](https://user-images.githubusercontent.com/53922851/87331651-48b6b380-c575-11ea-9912-de2bb0d39ec7.png)

음.. build 파일이 안올라가서 그런 것 같아요. 
내일 같이 보면 될 것 같습니다.
